title: Wutichai Tacha-chakorn # your name (or website title) here
logo: "images/Untitled design.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  About Me
  Google Data Analytics Professional Certificate, Excel & Python Clean and Analyze, and Create
Dashboard by Power BI. I help clients make better decisions with insights from great dashboards. And I
know what it takes to tell a powerful story with numbers and charts
  <br><br>
  Skills
  SQL, Python, R, EXCEL, GOOGLE SHEETS, Power BI, Tableau and Basic Statistics
  <br><br>
  <a href="https://www.linkedin.com/in/wutichai-tacha-chakorn-aa3ab82ba/">View My LinkedIn Profile</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-07ZDJEVM2V # your Google Analytics tracking ID here
